# Generated by Django 5.1.3 on 2024-12-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_created_at'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketregisterdetail',
            unique_together={('ticket_number', 'ticket', 'account')},
        ),
    ]
