# Generated by Django 5.1.6 on 2025-02-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticketregisterdetail_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketregisterdetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ticketregisterdetail',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
