# Generated by Django 5.1.6 on 2025-02-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticketregisterdetail_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketregisterdetail',
            name='order_person_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketregisterdetail',
            name='order_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketregisterdetail',
            name='order_person_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
