# Generated by Django 5.2 on 2025-04-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_updated_at_ticketregisterdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketregisterdetail',
            name='ticket_number',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
