# Generated by Django 5.2 on 2025-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_remark_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Review'), (2, 'Discussion'), (3, 'Accepted'), (4, 'Done'), (5, 'Rejected'), (6, 'Archived')], db_comment='Feedback status', default=0),
        ),
    ]
