# Generated by Django 5.2 on 2025-04-06 20:00

import django.db.models.deletion
import model_utils.fields
import uuid
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fcm_device', '0003_alter_fcmdevice_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Individual'), (1, 'Multiple')])),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Sent'), (2, 'Failed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'portal_notification',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Failed')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_history', to='fcm_device.fcmdevice')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='notification.notification')),
            ],
            options={
                'verbose_name': 'Notification History',
                'verbose_name_plural': 'Notification Histories',
                'db_table': 'portal_notification_history',
                'unique_together': {('notification', 'device')},
            },
        ),
    ]
