# Generated by Django 5.1.7 on 2025-04-05 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='created_at',
            field=models.DateTimeField(db_comment='Creation timestamp', default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Update timestamp'),
        ),
        migrations.AlterUniqueTogether(
            name='fcmdevice',
            unique_together={('device_id', 'token')},
        ),
    ]
