# Generated by Django 5.2 on 2025-04-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_device', '0002_fcmdevice_created_at_fcmdevice_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
