# Generated by Django 5.1.6 on 2025-02-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
