# Generated by Django 5.1.6 on 2025-03-04 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_info', '0003_eventschedule_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventschedule',
            name='color',
        ),
    ]
