# Generated by Django 5.1.5 on 2025-01-17 19:27

import django.db.models.deletion
import model_utils.fields
import portal.apps.faq.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.PositiveIntegerField(default=portal.apps.faq.models.FaqCategory.count)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'db_table': 'portal_faq_category',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.faqcategory')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('related_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.PositiveIntegerField(default=portal.apps.faq.models.Faq.count)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'portal_faq',
                'ordering': ['sort_order'],
            },
        ),
    ]
