# Generated by Django 5.1.5 on 2025-01-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
        ('instructor', '0002_instructor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='instructors',
            field=models.ManyToManyField(related_name='conference_instructors', to='instructor.instructor'),
        ),
    ]
