# Generated by Django 5.1.6 on 2025-02-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_conference_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
