# Generated by Django 5.1.3 on 2024-11-26 20:33

import django.db.models.deletion
import model_utils.fields
import uuid
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_account_email'),
        ('conference', '0001_initial'),
        ('instructor', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.conference')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor.instructor')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location')),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'db_table': 'portal_workshop',
                'ordering': ['title'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='WorkshopSchedule',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
            options={
                'verbose_name': 'Workshop Schedule',
                'verbose_name_plural': 'Workshop Schedules',
                'db_table': 'portal_workshop_schedule',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('unregistered_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('workshop_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshopschedule')),
            ],
            options={
                'verbose_name': 'Workshop Registration',
                'verbose_name_plural': 'Workshop Registrations',
                'db_table': 'portal_workshop_registration',
                'ordering': ['registered_at'],
                'unique_together': {('account', 'workshop_schedule')},
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
