# Generated by Django 5.1.3 on 2024-12-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='participants_limit',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
