# Generated by Django 5.1.5 on 2025-01-22 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('workshop', '0005_workshoptimeslot_remove_workshop_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='slido_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
