# Generated by Django 5.1.6 on 2025-02-21 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_alter_instructor_options_instructor_sort_order'),
        ('location', '0003_location_image'),
        ('workshop', '0007_alter_workshoptimeslot_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instructor.instructor'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='location.location'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop.workshoptimeslot'),
        ),
    ]
