# Generated by Django 5.1.6 on 2025-02-05 22:44

import django.core.validators
import django.db.models.deletion
import model_utils.fields
import portal.libs.consts.enums
import uuid
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAuthProvider',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=portal.libs.consts.enums.Provider.choices, max_length=16)),
                ('provider_id', models.CharField(max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Creation timestamp')),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AccountAuthProvider',
                'verbose_name_plural': 'AccountAuthProviders',
                'db_table': 'portal_account_auth_provider',
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='AccountPasswordAuth',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Creation timestamp')),
            ],
            options={
                'verbose_name': 'AccountPasswordAuth',
                'verbose_name_plural': 'AccountPasswordAuths',
                'db_table': 'portal_account_password_auth',
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.RemoveField(
            model_name='account',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='account',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='auth_provider',
        ),
        migrations.RemoveField(
            model_name='account',
            name='custom_claims',
        ),
        migrations.RemoveField(
            model_name='account',
            name='google_uid',
        ),
        migrations.RemoveField(
            model_name='account',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['phone_number'], name='portal_acco_phone_n_498d42_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='portal_acco_email_093d94_idx'),
        ),
        migrations.AddField(
            model_name='accountauthprovider',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AddField(
            model_name='accountpasswordauth',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
