# Generated by Django 5.1.6 on 2025-02-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accountauthprovider_accountpasswordauth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_service',
            field=models.BooleanField(db_comment='Is service', default=False),
        ),
    ]
