# Generated by Django 5.1.6 on 2025-02-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_is_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
