# Generated by Django 5.1.6 on 2025-02-18 02:59

import portal.libs.consts.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=portal.libs.consts.enums.Gender.choices, null=True),
        ),
    ]
