# Generated by Django 5.1.6 on 2025-02-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountauthprovider',
            name='provider_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
