# Generated by Django 5.2 on 2025-04-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_accountauthprovider_provider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='accountauthprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Last update timestamp'),
        ),
    ]
