# Generated by Django 5.1.5 on 2025-01-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
