# Generated by Django 5.1.6 on 2025-02-18 21:49

import portal.apps.instructor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructor_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['sort_order'], 'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.AddField(
            model_name='instructor',
            name='sort_order',
            field=models.PositiveIntegerField(default=portal.apps.instructor.models.Instructor.count),
        ),
    ]
