# Generated by Django 5.1.6 on 2025-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_alter_instructor_options_instructor_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
